# 45 프로미스

프로미스는 비동기 처리를 위한 또 다른 패턴이다.

## 45.1 비동기 처리를 위한 콜백 패턴의 단점

### 45.1.1 콜백 헬

비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다. 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.  
따라서 비동기 함수 내부의 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

예를 들어 `setTimeout` 함수의 콜백 함수는 `setTimeout` 함수가 종료된 이후에 호출된다.(비동기) 따라서 `setTimeout` 함수 내부의 콜백 함수에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

```js
const g = 0;

setTimeout(() => {
  g = 100;
}, 0);
console.log(g); // 0
```

GET 요청을 전송하고 서버의 응답을 전달받는 `get` 함수도 비동기 함수다. 비동기 함수인 이유는 함수 내부의 `onload` 이벤트 핸들러가 비동기로 동작하기 때문이다.  
해당 함수를 호출하면 요청을 전송하고 `onload` 이벤트 핸들러를 등록한 다음 `undefined`를 반환하고 즉시 종료된다.

```js
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.open = () => {
    if (xhr.status === 200) {
      return JSON.parse(xhr.response);
    }
    console.error(`${xhr.status} ${xhr.statusText}`);
  };
};

const response = get('https://jsonplaceholder.typicode.com/posts/1');
console.log(response);
```

`get` 함수가 호출되면 `XMLHttpRequest` 객체를 생성하고, HTTP 요청을 초기화한 후, 전송한다. 그리고 `xhr.onload` 이벤트 핸들러를 바인딩하고 종료한다. 이때 명시된 반환문이 없으므로 `undefined`를 반환한다.

이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문은 `get` 함수의 반환문이 아니다. 이는 `onload` 이벤트 핸들러를 `get`이 호출하는 것이 아니기 때문.  
상위 스코프의 변수에 할당해도 마찬가지다.

비동기 함수 `get`이 호출되면 함수 코드를 평가하는 과정에서 `get` 함수의 실행 컨텍스트가 생성되고 실행 컨텍스트 스택(콜 스택)에 푸시된다. 이후 함수 코드 실행과정에서 `onload` 이벤트 핸들러 프로퍼티에 바인딩된다.

함수가 종료하면 실행 컨텍스트가 콜 스택에서 팝되고 `console.log`가 호출된다. 이때 `console.log`의 실행 컨텍스트가 콜 스택에 푸시된다.

만약 `console.log` 실행전에 load 이벤트가 발생하더라도 태스크 큐에 저장되어 대기하다가 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다. 따라서 이미 `console.log`는 종료된 이후다.

이처럼 비동기 함수는 처리 결과를 외부에 반환할 수 없고 상위 스코프의 변수에 할당할 수도 없다. 후속 처리는 함수 내부에서 수행해야 한다는 뜻이다.  
이때 성공했을 때 호출될 콜백 함수와 실패했을 때 호출될 콜백 함수를 전달할 수 있다.

```js
const get = (url, successCallback, failureCallback) => {
  const xhr = new XMLHttpRequest();
  xhr.open('GET', url);
  xhr.send();

  xhr.open = () => {
    if (xhr.status === 200) {
      successCallback(JSON.parse(xhr.response));
    } else {
      failureCallback(xhr.status);
    }
  };
};

get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error);
```

이때 만약 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수가 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 콜백 함수 호출이 중첩되어 복잡도가 높아지는 **콜백 헬**이 발생한다

```js
get('/step1', (a) => {
  get(`/step2/${a}`, (b) => {
    get(`/step3/${b}`, (c) => {
      ...
    })
  })
})
```

### 45.1.2 에러 처리의 한계

비동기 처리를 위한 콜백 패턴의 문제점 중에서 가장 심각한 것은 에러 처리가 곤란하다는 것이다.

```js
try {
  setTimeout(() => {
    throw new Error('Error!');
  }, 1000);
} catch (e) {
  console.error(e);
}
```

위 예제의 에러는 캐치되지 않는다.  
`setTimeout`의 콜백 함수가 실행될 때 `setTimeout`은 이미 콜 스택에서 제거된 상태고 이는 콜백 함수를 호출한 것이 `setTimeout`이 아니라는 것을 의미한다.  
만약 콜백 함수의 호출자가 `setTimeout`이라면 콜 스택의 현재 실행 중인 실행 컨텍스트가 콜백 함수의 컨텍스트일 때 현재 실행 중인 실행 컨텍스트의 하위 실행 컨텍스트가 `setTimeout` 이어야 한다.

에러는 호출자 방향으로 전파된다. 하지만 하위 컨텍스트가 `setTimeout`가 아니기 때문에 catch 블록에서 캐치되지 않는다.(호출자가 아님)

## 45.2 프로미스의 생성

`Promise` 생성자 함수를 `new` 연산자와 함께 호출하면 프로미스를 생성한다.  
이것은 ECMAScript 사양에 정의된 표준 빌트인 객체다.

`Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수(executer라고도 부름)를 인수로 전달받는데 이 콜백 함수는 `resolve`와 `reject` 함수를 인수로 전달받는다.

```js
const promise = new Promise((resolve, reject) => {
  if (success) {
    resolve('success');
  } else {
    reject('fail');
  }
});
```

앞에서 살펴본 `get`을 프로미스를 사용해 다시 구현해 보면

```js
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.open = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response));
      }
      reject(new Error(xhr.status));
    };
  });
};

promiseGet('https://jsonplaceholder.typicode.com/posts/1');
```

비동기 함수인 `promiseGet`은 함수 내부에서 프로미스를 생성하고 반환하고 비동기 처리는 `Promise` 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행한다.

프로미스는 현재 비동기 처리가 어떻게 진행되고 있는지를 나타내는 상태 정보를 갖는다.

| 프로미스의 상태 정보 | 의미                                  | 상태 변경 조건                   |
| -------------------- | ------------------------------------- | -------------------------------- |
| pending              | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
| fulfilled            | 비동기 처리가 수행된 상태(성공)       | resolve 함수 호출                |
| rejected             | 비동기 처리가 수행된 상태(실패)       | reject 함수 호출                 |

- 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경한다.
- 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경한다.

이처럼 프로미스의 상태는 `resolve` 또는 `reject` 함수를 호출하는 것으로 결정된다.

그리고 fulfilled 또는 rejected 상태를 settled 상태라고 한다. 이것은 pending이 아닌 비동기 처리가 수행된 상태를 말한다.

## 45.3 프로미스의 후속 처리 메서드

프로미스는 처리 결과를 가지고 처리할 수 있는 후속 메서드 `then`, `catch`, `finally`를 제공한다.

프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.

### 45.3.1 Promise.prototype.then

1. 첫 번재 콜백 함수: 프로미스가 fulfilled 상태가 되면 호출. 이때 콜백 함수는 비동기 처리 결과를 인수로 전달받는다.
2. 두 번째 콜백 함수: 프로미스가 rejected 상태가 되면 호출. 이때 콜백 함수는 에러를 인수로 전달받는다.

```js
new Promise((resolve, reject) => {
  if (a > 0) {
    resolve('fulfilled');
  } else {
    reject(new Error('rejected'));
  }
}).then(
  (v) => console.log(v),
  (e) => console.error(e),
);
```

`then` 메서드는 언제나 프로미스를 반환한다. 만약 `then` 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 반환하고 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 `resolve` 또는 `reject` 하여 프로미스를 생성해 반환한다.

### 45.3.2 Promise.prototype.catch

`catch` 메서드는 한 개의 콜백 함수를 인수로 전달받는다. 이 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.

`then` 메서드와 마찬가지로 프로미스를 반환한다.

### 45.3.3 Promise.prototype.finally

`finally` 메서드는 한 개의 콜백 함수를 인수로 전달받는다. 이 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다. 마찬가지로 프로미스를 반환한다.

```js
const promiseGet = (url) => {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('GET', url);
    xhr.send();

    xhr.open = () => {
      if (xhr.status === 200) {
        resolve(JSON.parse(xhr.response));
      }
      reject(new Error(xhr.status));
    };
  });
};

promiseGet('https://jsonplaceholder.typicode.com/posts/1')
  .then((res) => console.log(res))
  .catch((err) => console.error(err))
  .finally(() => console.log('Bye!'));
```

## 45.4 프로미스의 에러 처리

프로미스의 비동기 처리 결과에 대한 후속 처리는 프로미스가 제공하는 후속 처리 메서드를 사용하여 수행한다. 이때 에러는 `catch` 메서드를 사용하거나 `then` 메서드의 두 번째 콜백 함수로 처리할 수 있다.

하지만 `then` 메서드의 두 번째 콜백 함수는 첫 번째 콜백 함수에서 발생한 에러를 캐치하지 못하므로 `catch` 메서드를 사용하는 것이 가독성이 좋고 명확하다.

## 45.5 프로미스 체이닝

```js
const url = 'https://jsonplaceholder.typicode.com';

promiseGet(`${url}/posts/1`)
  .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
  .then((userInfo) => console.log(userInfo))
  .catch((err) => console.error(err));
```

위 처럼 후속 처리 메서드 호출이 가능한 이유는 언제나 프로미스를 반환하기 때문이다. 만약 후속처리 메서드의 콜백 함수가 프로미스가 아닌 값을 반환하더라도 암묵적으로 `resolve` 또는 `reject` 하여 프로미스를 생성해 반환한다.  
이를 프로미스 체이닝이라 한다.

이러한 콜백 패턴의 가독성 문제를 `async/await`를 통해 해결할 수 있다.  
이것을 사용하면 후속 처리 메서드 없이 마치 동기 처럼 프로미스가 처리 결과를 반환하도록 구현할 수 있다.

```js
const url = 'https://jsonplaceholder.typicode.com';

(async () => {
  const { userId } = await promiseGet(`${url}/posts/1`);
  const userInfo = await promiseGet(`${url}/users/${userId}`);

  console.log(userInfo);
})();
```

## 45.6 프로미스의 정적 메서드

### 45.6.1 Promise.resolve / Promise.reject

`Promise.resolve`와 `Promise.reject` 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용한다.

`Promise.resolve` 메서드는 인수로 전달받은 값을 resolve하는 프로미스를 생성한다.

```js
const resolvedPromise = Promise.resolve([1, 2, 3]);
resolvedPromise.then(console.log); // [1, 2, 3]

const resolvedPromise2 = new Promise((resolve) => resolve([1, 2, 3]));
resolvedPromise2.then(console.log); // [1, 2, 3]
```

```js
// reject
const rejectedPromise = Promise.reject(new Error('Error!'));
rejectedPromise.catch(console.error); // Error: Error!
```

## 45.6.2 Promise.all

`Promise.all` 메서드는 여러 개의 비동기 처리를 모두 병렬 처리할 때 사용한다.

```js
const requestData1 = () => new Promise((resolve) => setTimeout(() => resolve(1), 3000));
const requestData2 = () => new Promise((resolve) => setTimeout(() => resolve(2), 2000));
const requestData3 = () => new Promise((resolve) => setTimeout(() => resolve(3), 1000));

const res = [];

requestData1()
  .then((data) => {
    res.push(data);
    return requestData2();
  })
  .then((data) => {
    res.push(data);
    return requestData3();
  })
  .then((data) => {
    res.push(data);
    console.log(res); // [1, 2, 3] => 약 6초 소요
  })
  .catch(console.error);
```

위 예제는 세 개의 비동기 처리를 순차적으로 처리한다.  
하지만 위 예제는 세 개의 비동기 처리가 서로 의존하지 않고 개별적으로 수행되므로 순차적으로 처리할 필요가 없다.

이때 `Promise.all`을 사용하면 여러 개의 비동기 처리를 모두 병렬 처리한다.

```js
Promise.all([requestData1(), requestData2(), requestData3()])
  .then(console.log) // [1, 2, 3] => 약 3초 소요
  .catch(console.error);
```

이 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달 받는다. 그리고 전달받은 **모든 프로미스가 모두 fulfilled 상태가 되면** 모든 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다.

위 예제의 경우 모든 처리에 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 첫 번째 프로미스의 처리 시간인 3초보다 조금 더 소요된다.  
이때 처리가 가장 늦더라도 첫 번째 프로미스가 `resolve`한 처리 결과부터 차례대로 배열에 저장해 그 배열을 `resolve` 하는 프로미스를 반환하므로 처리 순서가 보장된다.

만약 인수로 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 종료한다.

```js
Promise.all([
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 1')), 3000))
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 2')), 2000))
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 3')), 1000))
])
  .then(console.log)
  .catch(console.error) // Error: Error 3
```

그리고 이 메서드는 인수로 전달받은 이터러블의 요소가 프로미스가 아닌 경우 `Promise.resolve` 메서드를 통해 프로미스로 래핑한다.

```js
const githubIds = ['jeresig', 'ahejlsberg', 'circlewee'];

Promise.all(githubIds.map((id) => promiseGet(`https://api.github.com/users/${id}`)))
  .then((users) => users.map((user) => user.name))
  .then(console.log)
  .catch(console.error);
```

위 예제의 `Promise.all` 메서드는 `promiseGet` 함수가 반환한 3개의 프로미스로 이루어진 배열을 인수로 전달받고 이 프로미스들이 모두 fulfilled 상태가 되면 처리 결과를 배열에 저장해 새로운 프로미스를 반환한다.

### 45.6.3 Promise.race

`Promise.race` 메서드는 `Promise.all` 메서드와 동일하게 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 다만 이 메서드는 모든 프로미스가 fulfilled 상태가 되는 것을 기다리는 것이 아니라 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 `resolve`하는 새로운 프로미스를 반환한다.

```js
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000))
  new Promise((resolve) => setTimeout(() => resolve(2), 2000))
  new Promise((resolve) => setTimeout(() => resolve(3), 1000))
])
  .then(console.log) // 3
  .catch(console.error)
```

전달된 프로미스가 rejected 상태가 되면 `Promise.all` 메서드와 동일하게 에러를 `reject`하는 새로운 프로미스를 즉시 반환한다.

```js
Promise.race([
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 1')), 3000))
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 2')), 2000))
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error 3')), 1000))
])
  .then(console.log)
  .catch(console.error) // Error: Error 3
```

### 45.6.4 Promise.allSettled

`Promise.allSettled` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받는다. 그리고 전달받은 프로미스가 모두 `settled` 상태가 되면 처리 결과를 배열로 반환한다.

```js
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 1000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error('Error!')), 1000)),
]).then(console.log);
/*
[
  {status: 'fulfilled', value: 1},
  {status: 'rejected', reason: Error: Error! at ...}
]
*/
```

이 메서드가 반환한 배열에는 fulfilled 또는 rejected 산태와는 상관없이 `Promise.allSettled` 메서드가 인수로 전달받은 모든 프로미스들의 처리 결과가 모두 담겨 있다.

- fulfilled 상태: 상태를 나타내는 `status` 프로퍼티와 결과를 나타내는 `value` 프로퍼티를 갖는다.
- rejected 상태: 상태를 나타내는 `status` 프로퍼티와 에러를 나타내는 `reason` 프로퍼티를 갖는다.

## 45.7 마이크로태스크 큐

```js
setTimeout(() => console.log(1), 0);

Promise.resolve()
  .then(() => console.log(2))
  .then(() => console.log(3));
```

위 코드의 처리 결과는 2 -> 3 -> 1 순으로 출력된다. 그 이유는 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 마이크로태스크 큐에 저장되기 때문이다.

이것은 태스크 큐와 별개이며 그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러는 태스크 큐에 일시 저장된다.

콜백 함수나 이벤트 핸들러를 일시 저장한다는 점에서 태스크 큐와 동일하지만 마이크로 태스크 큐는 태스크 큐보다 우선순위가 높다. 즉, 이벤트 루프는 태스크 큐보다 마이크로태스크 큐에서 대기하고 있는 함수를 먼저 가져와 실행한다. 태스크 큐는 그 이후다.

## 45.8 fetch

`fetch` 함수는 `XMLHttpRequest` 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다. `XMLHttpRequest`보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.

`fetch` 함수는 HTTP 응답을 나타내는 `Response` 객체를 래핑한 `Promise` 객체를 반환한다.

```js
fetch('https://jsonplaceholser.typicode.com/todos/1').then((response) => console.log(response));
```

`Response` 객체는 HTTP 응답을 나타내는 다양한 프로퍼티를 제공한다.

`Response.prototype`에는 `Response` 객체에 포함되어 있는 HTTP 응답 몸체를 위한 다양한 메서드를 제공한다. 예를 들어, `fetch` 함수가 반환한 프로미스가 래핑하고 있는 MIME 타입이 `application/json`인 HTTP 응답 몸체를 취득하려면 `Response.prototype.json` 메서드를 사용한다.

```js
fetch('https://jsonplaceholser.typicode.com/todos/1')
  .then((response) => response.json())
  .then((json) => console.log(json))
  .catch(() => console.log('error'));
```

만약 URL을 잘못 지정했다고 가정하면 404 Not Found 에러가 발생하고 `catch` 후속 처리 메서드에 의해 `'error'`가 출력될 것 처럼 보이지만 `'ok'`가 출력된다.

`fetch` 함수가 반환하는 프로미스는 기본적으로 404 Not Found나 500 Internal Server Error와 같은 HTTP 에러가 발생하도 에러를 `reject`하지 않고 불리언 타입의 `ok` 상태를 `false`로 설정한 `Response` 객체를 `resolve`한다.  
오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 `reject`한다.

```js
fetch('https://jsonplaceholser.typicode.com/XXXXX/1')
  .then((response) => {
    if (!response.ok) throw new Error(response.statusText);
    return response.json();
  })
  .then((json) => console.log(json))
  .catch((err) => console.error(err));
```
