# 45장 프로미스

## 📂 45.1 비동기 처리를 위한 콜백 패턴의 단점
### 콜백 헬
#### 비동기 함수
- 함수 내부에 비동기로 동작하는 코드를 포함한 함수
- 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료
⇒ 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료됨
- 따라서 비동기 함수 내부의 비동기로 동작하는 코드에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당할 수 없다.

#### 비동기 함수 내부의 처리 결과를 상위 스코프의 변수에 할당할 수 없는 이유

```javascript
// 서버의 응답을 상위 스코프의 변수로 할당
let todos;

// GET 요청을 위한 비동기 함수
const get = (url) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // ① 서버의 응답을 상위 스코프 변수에 할당
      todos = JSON.parse(xhr.response);
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

// idrk 1인 post 취득
get("https://jsonplaceholder.typicode.com/posts/1");
console.log(todos); // ② undefined
```

- 비동기 함수 `get` 호출
  - `get` 함수의 실행 컨텍스트가 생성
  - 실행 컨텍스트 스택에 푸시
  - 이후 함수 코드 실행 과정에서 `xhr.onload` 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩된다.
  - `get` 함수가 종료하면 `get` 함수의 실행 컨텍스트가 콜 스택에서 팝
- 곧바로 ②의 `console.log` 호출
  - `console.log`의 실행 컨텍스트 생성
  - 실행 컨텍스트 스택에 푸시
  - `console.log`가 호출되기 직전에 load 이벤트가 발생했더라도 `xhr.onload` 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러는 `console.log`보다 먼저 실행되지 않는다.
- 서버로부터 응답이 도착하면 `xhr` 객체에서 load 이벤트 발생
  - 이때 `xhr.onload` 핸들러 프로퍼티에 바인딩한 이벤트 핸들러가 즉시 실행되지 않는다.
  - `xhr.onload` 이벤트 핸들러는 load 이벤트가 발생하면 일단 태스크 큐에 저장되어 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행
  - 이벤트 핸들러도 함수이므로 `이벤트 핸들러의 평가 → 이벤트 핸들러의 실행 컨텍스트 생성 → 콜 스택에 푸시 → 이벤트 핸들러 실행` 과정을 거친다.
- `xhr.onload` 이벤트 핸들러가 실행되는 시점에 콜 스택이 빈 상태여야 하므로 ②의 `console.log`는 이미 종료된 이후다.
⇒ `xhr.onload` 이벤트 핸들러에서 상위 스코프의 변수에 서버의 응답 결과를 할당하기 전에 `console.log`가 먼저 호출되어 `undefined`가 출력

따라서, **비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 비동기 함수 내부에서 수행해야 한다.**
- 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적
- 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수와 실패하면 호출될 콜백 함수를 전달

#### 콜백 헬<sup>callback hell</sup>
- 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상

```javascript
const get = (url, callback) => {
  const xhr = new XMLHttpRequest();
  xhr.open("GET", url);
  xhr.send();

  xhr.onload = () => {
    if (xhr.status === 200) {
      // 서버의 응답을 콜백 함수에 전달하면서 호출하여 응답에 대한 후속 처리
      callback(JSON.parse(xhr.response));
    } else {
      console.error(`${xhr.status} ${xhr.statusText}`);
    }
  };
};

const url = "https://jsonplaceholder.typicode.com";

// id가 1인 post의 userId 취득
get(url + "/posts/1", ({ userId }) => {
  console.log(userId);

  // post의 userId를 통해 user 정보 취득
  get(url + "/users/" + userId, (userInfo) => {
    console.log(userInfo);
  });
});
```

### 에러 처리의 한계
- 콜백 패턴의 문제점은 에러 처리가 곤란하다는 것이다.

```javascript
try {
  // 1초 후 콜백 함수가 실행되도록 타이머 설정
  setTimeout(() => { throw new Error("Error!"); }, 1000);
} catch (e) {
  // 에러를 캐치하지 못함
  console.error("캐치한 에러", e);
}
```

- **에러는 호출자<sup>caller</sup> 방향으로 전파**
  - 콜 스택 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파
- `setTimeout` 함수의 콜백 함수가 실행될 때 `setTimeout` 함수는 이미 콜 스택에서 제거된 상태
  - `setTimeout`의 콜백 함수를 호출한 것이 `setTimeout` 함수가 아니라는 것을 의미
- `setTimeout` 함수의 콜백 함수가 발생시킨 에러는 `catch` 블록에서 캐치되지 않는다.

## 📂 45.2 프로미스의 생성
#### `Promise`
- ES6에서 도입된 ECMAScript 사양에 정의된 표준 빌트인 객체
- `Promise` 생성자 함수를 `new` 연산자와 함께 호출하여 `Promise` 객체 생성
- `Promise` 생성자 함수는 비동기 처리를 수행할 콜백 함수 `resolve`, `reject` 함수를 인수로 전달 받음
  - 비동기 처리가 성공하면 `resolve` 함수 호출
  - 비동기 처리가 실패하면 `reject` 함수 호출

#### 비동기 처리 상태 정보
- 프로미스는 현재 비동기 처리의 진행 상태 정보를 갖는다.
  | 프로미스의 상태 정보 | 의미 | 상태 변경 조건 |
  | -------- | -------- | -------- |
  | `pending` | 비동기 처리가 아직 수행되지 않은 상태 | 프로미스가 생성된 직후 기본 상태 |
  | `fulfilled` | 비동기 처리가 수행된 상태(성공) | `resolve` 함수 호출 |
  | `rejected` | 비동기 처리가 수행된 상태(실패) | `reject` 함수 호출 |
- 생성된 직후의 프로미스는 기본적으로 `pending` 상태
- 이후 비동기 처리가 수행되면 그 결과에 따라 프로미스의 상태가 변경
  - 비동기 처리 성공 : `resolve` 함수를 호출하여 프로미스를 `fulfilled` 상태로 변경
  - 비동기 처리 실패 : `reject` 함수를 호출하여 프로미스를 `rejected` 상태로 변경
- `settled` 상태
  - 비동기 처리가 수행된 상태
  - `fulfilled` 또는 `rejected` 상태와 상관없이 `pending`이 아닌 상태
  - 프로미스는 `pending` 상태에서 `settled` 상태로 변할 수 있지만, 일단 `settled` 상태가 되면 더는 다른 상태로 변화할 수 없다.

⇒ 프로미스는 **비동기 처리 상태**와 **처리 결과**를 관리하는 객체

## 📂 45.3 프로미스의 후속 처리 메서드
- 프로미스는 후속 메서드 `then`, `catch`, `finally`를 제공
- **프로미스의 비동기 처리 상태가 변화하면 후속 처리 메서드에 인수로 전달한 콜백 함수가 선택적으로 호출된다.**
  - 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달
  - 모든 후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작

### `Promise.prototype.then`
- `then` 메서드는 두 개의 콜백 함수를 인수로 전달받는다.
  - 첫 번째 콜백 함수
    - 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수
    - 프로미스가 `fulfilled` 상태가 되면 호출
    - 이때 콜백 함수는 프로미스의 비동기 **처리 결과**를 인수로 전달받는다.
  - 두 번째 콜백 함수
    - 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수
    - 프로미스가 `rejected` 상태가 되면 호출
    - 이때 콜백 함수는 프로미스의 **에러**를 인수로 전달받는다.

```javascript
new Promise(resolve => resolve('fulfilled'))
  .then(v => console.log(v), e => console.error(e)); // fulfilled

new Promise((_, reject) => reject(new Error('rejected')))
  .then(v => console.log(v), e => console.error(e)); // Error: rejected
```

### `Promise.prototype.catch`
- `catch` 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- `catch` 메서드의 콜백 함수는 프로미스가 `rejected` 상태인 경우에만 호출
- `catch` 메서드는 `then(undefined, onRejected)`과 동일하게 동작

```javascript
new Promise((_, reject) => reject(new Error('rejected')))
  .catch(e => console.error(e)); // Error: rejected
```

### `Promise.prototype.finally`
- `finally` 메서드는 한 개의 콜백 함수를 인수로 전달받는다.
- `finally` 메서드의 콜백 함수는 프로미스의 성공 또는 실패와 상관없이 무조건 한 번 호출된다.
  - 프로미스의 상태와 상관없이 공통적으로 수행해야할 처리 내용이 있을 때 유용

```javascript
new Promise(() => {})
  .finally(() => console.log('finally')); // finally
```


## 📂 45.4 프로미스의 에러 처리
#### `then` 메서드의 두 번째 콜백 함수
- 비동기 처리에서 발생한 에러는 `then` 메서드의 두 번째 콜백 함수로 처리 가능
- 단, 첫 번째 콜백 함수에서 발생한 에러는 캐치하지 못한다.
- 코드의 가독성이 좋지 않다.

```javascript
const wrongUrl = 'https://wrongurl.com';

promiseGet(wrongUrl).then(
  res => console.log(res), // 첫 번째 콜백 함수에서 발생한 에러는 캐치하지 못한다.
  error => console.log(error)
)
```

#### `catch` 메서드
- 비동기 처리에서 발생한 에러는 `catch` 메서드를 사용해 처리 가능
- 비동기 처리에서 발생한 에러(rejected 상태)뿐만 아니라 `then` 메서드 내부에서 발생한 에러까지 모두 캐치 가능
- `then` 메서드에 두 번째 콜백 함수를 전달하는 것 보다 가독성이 좋고 명확하다.
- `catch` 메서드를 호출하면 내부적으로 `then(undefined, onRejected)`을 호출

```javascript
const wrongUrl = 'https://wrongurl.com';

promiseGet(wrongUrl)
  .then(res => console.log(res))
  .catch(error => console.log(error));

// 위 코드의 내부적인 코드 처리
promiseGet(wrongUrl)
  .then(res => console.log(res))
  .then(undefined, error => console.log(error));
```

## 📂 45.5 프로미스 체이닝<sup>promise chaining</sup>
- `then`, `catch`, `finally` 후속 처리 메서드를 연속적으로 호출
- 후속 처리 메서드는 콜백 함수가 반환한 프로미스 반환
  - 콜백 함수가 프로미스가 아닌 값을 반환하더라도 그 값을 암묵적으로 `resolve` 또는 `reject`하여 프로미스를 생성해 반환
- 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리하므로 콜백 헬이 발생하지 않는다.
  - 프로미스도 콜백 패턴을 사용하므로 콜백 함수를 사용하지 않는 것은 아니다.
- ES8에 **`async/await`** 도입
  - 프로미스의 후속 처리 메서드 없이 마치 동기 처리처럼 프로미스가 처리 결과를 반환하도록 구현
  - `async/await`도 프로미스를 기반으로 동작

## 📂 45.6 프로미스의 정적 메서드
### `Promise.resolve` / `Promise.reject`
- 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용
- `Promise.resolve` 메서드 : 인수로 전달받은 값을 `resolve`하는 프로미스 생성
  ```javascript
  const resolvePromise = Promise.resolve([1, 2, 3]);
  resolvePromise.then(console.log); // [1, 2, 3]

  // 위와 동일한 동작
  const resolvePromise = new Promise((resolve) => resolve([1, 2, 3]));
  resolvePromise.then(console.log); // [1, 2, 3]
  ```
- `Promise.reject` 메서드 : 인수로 전달받은 값을 `reject`하는 프로미스 생성
  ```javascript
  const rejectedPromise = Promise.reject(new Error("Error!"));
  rejectedPromise.catch(console.log); // Error: Error!

  // 위와 동일한 동작
  const rejectedPromise = new Promise((_, reject) => reject(new Error("Error!")));
  rejectedPromise.catch(console.log); // Error: Error!
  ```

### `Promise.all`
- 여러 개의 비동기 처리를 모두 병렬<sup>parallel</sup> 처리할 때 사용
- `Promise.all` 메서드는 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받고, 전달받은 모든 프로미스가 모두 `fulfilled` 상태가 되면 모든 처리 결과를 배열에 저장해 새로운 프로미스 반환하는 메서드
- 인수로 전달받은 배열의 모든 프로미스가 모두 `fulfilled` 상태가 되면 종료
  - `Promise.all` 메서드가 종료하는데 걸리는 시간은 가장 늦게 `fulfilled` 상태가 되는 프로미스의 처리시간보다 조금 더 길다.
- 모든 프로미스가 `fulfilled` 상태가 되면 `resolve`된 처리 결과를 모두 배열에 저장해 새로운 프로미스 반환
- 첫 번째 프로미스가 가장 나중에 `fulfilled` 상태가 되어도 `Promise.all` 메서드는 첫 번째 프로미스가 `resolve`한 처리 결과부터 차례대로 배열에 저장하므로 **처리 순서가 보장**된다.
  ```javascript
  const requestData1 = () =>
    new Promise((resolve) => setTimeout(() => resolve(1), 3000));
  const requestData2 = () =>
    new Promise((resolve) => setTimeout(() => resolve(2), 2000));
  const requestData3 = () =>
    new Promise((resolve) => setTimeout(() => resolve(3), 1000));

  Promise.all([requestData1(), requestData2(), requestData3()])
    .then(console.log) // [1, 2, 3]
    .catch(console.error);
  ```
- 인수로 전달받은 배열의 프로미스가 하나라도 `reject` 상태가 되면 나머지 프로미스가 `fulfilled` 상태가 되는 것을 기다리지 않고 즉시 종료
  - 가장 먼저 `reject` 상태가 된 프로미스의 에러가 `catch` 메서드로 전달된다.
  ```javascript
  Promise.all([
    new Promise((_, reject) => setTimeout(() => reject(new Error("Error 1")), 3000)),
    new Promise((_, reject) => setTimeout(() => reject(new Error("Error 2")), 2000)),
    new Promise((_, reject) => setTimeout(() => reject(new Error("Error 3")), 1000)),
  ])
    .then(console.log)
    .catch(console.error); // Error: Error 3
  ```
- 인수로 전달받은 이터러블의 요소가 프로미스가 아닌 경우 `Promise.resolve` 메서드를 통해 프로미스로 래핑
  ```javascript
  Promise.all([
    1, // Promise.resolve(1)
    2, // Promise.resolve(2)
    3, // Promise.resolve(3)
  ])
    .then(console.log)
    .catch(console.error);
  ```

### `Promise.race`
- 프로미스를 요소로 갖는 배열 들의 이터러블을 인수로 전달받아 가장 먼저 `fulfilled` 상태가 된 프로미스 처리 결과를 `resolve`하는 새로운 프로미스 반환
- 인수로 전달받은 배열의 프로미스가 하나라도 `reject` 상태가 되면 에러를 `reject`하는 새로운 프로미스 즉시 반환(`Promise.all` 메서드와 동일)
```javascript
Promise.race([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)),
  new Promise((resolve) => setTimeout(() => resolve(2), 2000)),
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)),
])
  .then(console.log) // 3
  .catch(console.error);
```

### `Promise.allSettled`
- 프로미스를 요소로 갖는 배열 등의 이터러블을 인수로 전달받아 전달받은 프로미스가 모두 `settled` 상태가 되면 처리 결과를 배열로 반환
- ES11(ECMAScript 2020)에 도입, IE를 제외한 대부분의 모던 브라우저에서 지원
- 프로미스의 처리 결과를 나타내는 객체
  - 프로미스가 `fulfilled` 상태인 경우, 비동기 처리 상태를 나타내는 `status` 프로퍼티와 처리 결과를 나타내는 `value` 프로퍼티를 갖는다.
  - 프로미스가 `rejected` 상태인 경우, 비동기 처리 상태를 나타내는 `status` 프로퍼티와 에러를 나타내는 `reason` 프로퍼티를 갖는다.

```javascript
Promise.allSettled([
  new Promise((resolve) => setTimeout(() => resolve(1), 2000)),
  new Promise((_, reject) => setTimeout(() => reject(new Error("Error!")), 1000)),
]).then(console.log);
/*
[
  0: {status: 'fulfilled', value: 1}
  1: {status: 'rejected', reason: Error: Error! at <anonymous>:3:54}
]
*/
```